# Generated by Django 5.2.10 on 2026-01-20 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='club',
            options={'ordering': ['name'], 'verbose_name': 'Информация о фитнес-центре', 'verbose_name_plural': 'Информация о фитнес-центре'},
        ),
        migrations.AlterModelOptions(
            name='historicalclub',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Информация о фитнес-центре', 'verbose_name_plural': 'historical Информация о фитнес-центре'},
        ),
        migrations.AddField(
            model_name='club',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание фитнес-центра'),
        ),
        migrations.AddField(
            model_name='historicalclub',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание фитнес-центра'),
        ),
        migrations.AlterField(
            model_name='club',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='clubs/', verbose_name='Фото фитнес-центра'),
        ),
        migrations.AlterField(
            model_name='club',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название фитнес-центра'),
        ),
        migrations.AlterField(
            model_name='historicalclub',
            name='image',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Фото фитнес-центра'),
        ),
        migrations.AlterField(
            model_name='historicalclub',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название фитнес-центра'),
        ),
    ]
