# Generated by Django 5.2.10 on 2026-01-20 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0002_alter_club_options_alter_historicalclub_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classbooking',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время начала'),
        ),
        migrations.AddField(
            model_name='classbooking',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время окончания'),
        ),
        migrations.AlterUniqueTogether(
            name='classbooking',
            unique_together={('user', 'fitness_class', 'start_time')},
        ),
    ]
