# Generated by Django 5.2.10 on 2026-01-20 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0003_add_start_end_time_to_classbooking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fitnessclass',
            name='title',
        ),
        migrations.RemoveField(
            model_name='fitnessclass',
            name='description',
        ),
        migrations.RemoveField(
            model_name='fitnessclass',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='fitnessclass',
            name='end_time',
        ),
        migrations.AlterModelOptions(
            name='fitnessclass',
            options={'ordering': ['-created_at'], 'verbose_name': 'Занятие', 'verbose_name_plural': 'Занятия'},
        ),
    ]
