# Generated by Django 5.2.10 on 2026-01-20 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0004_remove_fields_from_fitnessclass'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classbooking',
            options={'ordering': ['-created_at'], 'verbose_name': 'Запись на занятие', 'verbose_name_plural': 'Записи на занятия'},
        ),
        migrations.AlterModelOptions(
            name='fitnessclass',
            options={'ordering': ['-created_at'], 'verbose_name': 'Занятие', 'verbose_name_plural': 'Занятия'},
        ),
        migrations.AlterModelOptions(
            name='historicalfitnessclass',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Занятие', 'verbose_name_plural': 'historical Занятия'},
        ),
        migrations.AlterModelOptions(
            name='trainer',
            options={'ordering': ['user__full_name'], 'verbose_name': 'Тренер', 'verbose_name_plural': 'Тренеры'},
        ),
        migrations.AlterModelOptions(
            name='workouttype',
            options={'ordering': ['name'], 'verbose_name': 'Занятие', 'verbose_name_plural': 'Занятия'},
        ),
        migrations.AlterField(
            model_name='classbooking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_bookings', to='fitness.user', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='favoriteclass',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_classes', to='fitness.user', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='fitnessclass',
            name='workout_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fitness.workouttype', verbose_name='Занятие'),
        ),
        migrations.AlterField(
            model_name='historicalfitnessclass',
            name='workout_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='fitness.workouttype', verbose_name='Занятие'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='fitness.user', verbose_name='Пользователь'),
        ),
    ]
