# Generated by Django 5.2.10 on 2026-01-22 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0005_alter_classbooking_options_and_more'),
    ]

    operations = [
        # Поля description, end_time, start_time, title уже удалены из HistoricalFitnessClass
        # в предыдущих миграциях, поэтому пропускаем их удаление
        migrations.AlterField(
            model_name='club',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='clubs/', verbose_name='Фото клуба'),
        ),
        migrations.AlterField(
            model_name='club',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название клуба'),
        ),
        migrations.AlterField(
            model_name='fitnessclass',
            name='capacity',
            field=models.PositiveIntegerField(default=20, verbose_name='Максимум участников'),
        ),
        migrations.AlterField(
            model_name='historicalclub',
            name='image',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Фото клуба'),
        ),
        migrations.AlterField(
            model_name='historicalclub',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название клуба'),
        ),
        migrations.AlterField(
            model_name='historicalfitnessclass',
            name='capacity',
            field=models.PositiveIntegerField(default=20, verbose_name='Максимум участников'),
        ),
    ]
